### PR TITLE
add deployment for dev as well

### LINKED ISSUE #42: Add auto deployment to Expo for develop and master branch
By using the new itp-react-native-scripts module

### PR DESCRIPTION
**Pull request by easybird**
This PR closes #42

### CODE REVIEW

**Comment by easybird** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@itpocket/white-label-event-mobile-app-feature-42-auto-deploy-dev

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by thibmaek** [comment]
On failing build:

```bash
if [["$encrypted_a3f2a9459865_key" ]]; then if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then npm run deploy:pr; else if [[ "$TRAVIS_BRANCH" = "develop" ]]; then npm run deploy; else if [[ "$TRAVIS_BRANCH" = "master" ]]; then npm run deploy; fi
```

Might be better to abstract this to a shell script rather than having an ugly inliner

**Comment by easybird** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@itpocket/white-label-event-mobile-app-feature-42-auto-deploy-dev

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by easybird** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@itpocket/white-label-event-mobile-app-feature-42-auto-deploy-dev

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by easybird** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@itpocket/white-label-event-mobile-app-feature-42-auto-deploy-dev

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Pull request merged**
