### PR TITLE
🤓Add contributors to the repo automatically

### PR DESCRIPTION
**Pull request by thibmaek**
This automatically adds people who have contributed to our repo in the `CONTRIBUTORS.md` file.
Just something fun I thought I'd add in, we could for example run this on a pre-commit hook, bot, cron or post CI or something?

Let me know what you dudes think.

### CODE REVIEW

**Comment by easybird** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@itpocket/white-label-event-mobile-app-feature-add-contributors

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by thibmaek** [comment]
@easybird Jup!

**Comment by easybird** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@itpocket/white-label-event-mobile-app-feature-add-contributors

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by easybird** [comment]
@thibmaek can you just run your command on this PR? Then the current contributors will be visible already. For now, imo, this is sufficient to merge this PR. The automation can be added later.

**Pull request merged**
