### PR TITLE
Feature/44 add firebase subscriptions and make firebase optional

### LINKED ISSUE #44: Firebase should not be required to run the app during dev
Allow for a kind of demo mode to develop easily without having to constantly have Firebase active.

### PR DESCRIPTION
**Pull request by easybird**
This PR closes #44 
pr_demo

### CODE REVIEW

**Comment by devopsITP** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@itpocket/white-label-event-mobile-app-feature-44-make-firebase-optional

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by easybird** [comment]
styling issue in de gif is fixed

**Comment by devopsITP** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@itpocket/white-label-event-mobile-app-feature-44-make-firebase-optional

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by devopsITP** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@itpocket/white-label-event-mobile-app-feature-44-make-firebase-optional

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by easybird** [comment]
Will merge this and add todo's this weekend for an extra story: cleanup Flow, naming conventions (use session in stead of events), ...

**Pull request merged**
