### PR TITLE
Add templates for OSS contribution guidelines on Github

### PR DESCRIPTION
**Pull request by thibmaek**
Pitch in, feel free to change (after discussion)

### CODE REVIEW

**Comment by easybird** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@itpocket/white-label-event-mobile-app-feature-github-meta

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by easybird** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@itpocket/white-label-event-mobile-app-feature-github-meta

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by easybird** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@itpocket/white-label-event-mobile-app-feature-github-meta

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by thibmaek** [comment]
Thanks for the keen bird eye Jonathan 👁‍🗨

**Pull request merged**
